import { Inter } from "next/font/google";
import "./globals.css";
import SessionProvider from "@/components/session/SessionProvider"
import { getServerSession } from "next-auth";
import RecoilRoot from "@/components/recoilState/RecoilState";
import { authOptions } from "./api/auth/[...nextauth]/route";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Hungry Harbor",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={`${inter.className} `}>
        <SessionProvider session={session}>
          <RecoilRoot>
            {children}
          </RecoilRoot>
        </SessionProvider>
      </body>
    </html>
  );
}
